# Generated by Django 2.1.1 on 2018-10-20 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('last_saved', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gmpassword', models.CharField(max_length=100)),
                ('playerpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('PL', 'Player'), ('GM', 'GameMaster'), ('SPEC', 'Spectator')], default='PL', max_length=4)),
                ('created', models.DateField(auto_now_add=True)),
                ('last_saved', models.DateField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tth_backend.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('datasheet', models.TextField(max_length=65535)),
                ('created', models.DateField(auto_now_add=True)),
                ('last_saved', models.DateField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tth_backend.CampaignParticipant')),
            ],
        ),
        migrations.CreateModel(
            name='MainNPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('datasheet', models.TextField(max_length=65535)),
                ('is_public', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('last_saved', models.DateField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tth_backend.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleNPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('datasheet', models.TextField(max_length=65535)),
                ('is_public', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('last_saved', models.DateField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tth_backend.Campaign')),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='mycampaigns',
            field=models.ManyToManyField(to='tth_backend.Campaign'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
