# Generated by Django 2.1.1 on 2018-10-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tth_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='story',
            field=models.TextField(default='olipa kerran kikkeliskokkelis', max_length=65535),
            preserve_default=False,
        ),
    ]
