# Generated by Django 2.1.1 on 2018-10-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tth_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='shortdescription',
            field=models.CharField(default='Short description', max_length=150),
            preserve_default=False,
        ),
    ]
