# Generated by Django 2.1.1 on 2018-10-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tth_backend', '0002_campaign_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignparticipant',
            name='campaign_notes',
            field=models.TextField(default='these are my hurr durr durr notes about my hurr durr campaign', max_length=32767.5),
            preserve_default=False,
        ),
    ]
